### PR TITLE
added previous song button

### PR DESCRIPTION
**Pull request by sabarasaba**
Hey man ! I saw your post on reddit and I know that this isnt much, but I wanted to contribute with something. 
So I added a "Previous Song" button, but the SVG image is the same as the one in the "Next Song" button becouse I have no idea how to use those SVG elements. And once you got that fixed, i think you can close this issue: https://github.com/MeoMix/SongBuzz/issues/4 .

Later !

### CODE REVIEW

**Comment by MeoMix** [comment]
Awesome! I'm on my lunch break right now so I can't quite check this out yet, but I will definitely have a look-see after work. Thank you very much for your contribution, it is appreciated! :)

**Comment by MeoMix** [comment]
I merged the code and flipped the SVG paths for the rewind icon. Looks good, thanks! The only thing I can think of is that at some point I will need to implement the logic of "Did you mean to skip to the beginning of /this/ song or did you want to skip to the previous song?" which (I believe) is dependent on how much time has elapsed in the currently playing song.

**Comment by sabarasaba** [comment]
Awesome! Im gonna start working on the server app tomorrow. If its ok with you I would like to do it with node.js and build up a restful api to post and get playlists (as a json response) and get a  "top10 playlists" or something like that. 
And once we got that working we could deploy it to heroku or nodejitsu and start looking for some ways to implement it on the extension. I also would love the possibility to do lastfm scrobblings. So once we got the playlist thing working, im down for coding the lastfm integration =D

**Comment by MeoMix** [comment]
Cool!! :)

I have absolutely no experience with Node.js, but I was planning on learning it to create the server -- we're of the same mindset.

Yes, agreed that those sound like solid first features for the server. :) And yeah! I think one of the best features of this product is its ability to (relatively easily compared to other products..) integrate other song playing information. Go for it re-lastfm, I'll be watching! :D

**Comment by misostc** [comment]
To keep up with the UI's style, you should add "border-right: 1px solid #fff" to the previous button css style.

**Comment by MeoMix** [comment]
Added the CSS fix. Thanks for the sharp eye.

**Pull request merged**
